# Book settings
title: The Astrobook
author: Jorge M.G.
logo: dwg/png/astro_logo.png
exclude_patterns: ["README.md", "CONTRIBUTING.md"]

html:
  home_page_in_navbar: false

latex:
  latex_documents:
    targetname: astrobook.tex
