name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install Makefile and asymptote software
    - name: Install Makefile and asymptote
      run: |
        sudo apt-get install build-essential
        sudo apt-get install asymptote

    # Install Python dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    # Build the book
    - name: Build the book
      run: |
        make clean
        make html

    # Deploys book's HTML to github-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: astrobook/astrobook.github.io
        publish_branch: master
        publish_dir: ./_build/html

